title: Reshma Kelkar # your name (or website title) here
logo: "/images/smallR.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
    Data Science @ UChicago (Dec'20)
    Healthcare | NLP | Recommendation
    <br>
    <a href="https://www.linkedin.com/in/reshma-kelkar-71244919/">LinkedIn Profile</a> 
google_analytics: 149789775 # your Google Analytics tracking ID here
theme: jekyll-theme-minimal