title: Reshma Patil # your name (or website title) here
logo: "/images/my_logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
    Data Science Lead @ Amazon
    
    Search - LLM | Ranking & Recommendation Systems | Causal Inference
    <br>
    <a href="https://www.linkedin.com/in/reshma-kelkar-71244919/">LinkedIn Profile</a> 

theme: jekyll-theme-minimal
google_analytics: 149789775 # your Google Analytics tracking ID here
